server:
  port: 8084

spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_finance?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: localhost
      password: root
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        enabled: false
        import-check:
          enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          multiplier: 2.0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true

logging:
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
