server:
  port: 8088

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  config:
    import: nacos:gateway-service.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
        group: DEFAULT_GROUP
    sentinel:
      transport:
        dashboard: localhost:8080
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**,/api/user/**,/api/customer/**
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/api/room/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: finance-service
          uri: lb://finance-service
          predicates:
            - Path=/api/finance/**
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/api/system/**
        - id: ai-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/ai/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

logging:
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
